// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbrfhdazyixuvlxgcfoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxicmZoZGF6eWl4dXZseGdjZm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODAwNjIsImV4cCI6MjA2NzI1NjA2Mn0.skPfCeC8VjIjD0t_OQPYux-87XLGJtg5ZhxL0gYxXoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});